# Generated by Django 5.0.14 on 2026-03-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("creditos", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fecha_matricula", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "duracion",
                    models.PositiveSmallIntegerField(help_text="En semestres"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="productos",
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tienda.curso"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.estudiante",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="estudiante",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tienda.programa"
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="tienda.programa",
            ),
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
        migrations.AddConstraint(
            model_name="inscripcion",
            constraint=models.UniqueConstraint(
                fields=("estudiante", "curso"), name="unique_estudiante_curso"
            ),
        ),
    ]
